name: Documentation checks

on:
  pull_request:
    branches: 
      - main
    paths:
      - '**/*.md'

approval:
  require_face_check: false
  credential_types:
    - Contractor

notifications:
  channel_name: ghapp
