name: Secure Code

on:
  pull_request:
    branches: 
      - main
    paths:
      - '**/*.cs'

approval:
  require_face_check: false
  credential_types:
    - Technician

notifications:
  channel_name: ghapp
