name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: deploy
        run: echo "Pretend we're doing a deployment"
